name: deploy

on: 
  push:
    branch:
      - main

jobs:
  create-deplopment-artifacts:
    name: Create deplopment artifacts
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
